[package]
name = "bpe"
version = "0.1.0"
edition = "2024"

[lib]
name = "_bpe_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["extension-module", "abi3-py313"] }
