[project]
name = "bytetok"
version = "0.1.0"
description = "A modular byte-level BPE tokenizer library for rapid prototyping and research."
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
]
authors = [{ name = "Vihanga Malaviarachchi" }]
requires-python = ">=3.14"
dependencies = [
    "regex>=2026.1.15",
    "tiktoken>=0.12.0",
]


[tool.setuptools]
license-files = ["LICENSE"]


[project.optional-dependencies]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
]
train = [
    "datasets>=4.5.0",
]

[project.scripts]
bytetok = "bytetok.tokenizers.basic:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"